# Generated by Django 2.1.7 on 2019-09-08 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmdt_name', models.CharField(max_length=25, verbose_name='commander name')),
                ('kmdt_rank', models.CharField(choices=[('Lt.z.S', 'Lt.z.S'), ('Olt.z.S', 'Olt.z.S'), ('KptLt', 'KptLt'), ('KKpt', 'KKpt')], max_length=10, verbose_name='commander rank')),
                ('bt_name', models.CharField(max_length=4, verbose_name='vessel name')),
                ('bt_class', models.CharField(choices=[('U', 'U'), ('UB', 'UB'), ('UC', 'UC')], max_length=10, verbose_name='uboot class')),
                ('crew_quality', models.CharField(choices=[('Green', 'Green'), ('Trained', 'Trained'), ('Veteran', 'Veteran'), ('Elite', 'Elite')], default=1, max_length=10, verbose_name='crew quality')),
                ('deck_gun', models.CharField(choices=[('3.7cm', '3.7cm'), ('8.8cm', '8.8cm'), ('10.5cm', '10.5cm'), ('15cm', '15cm')], default=0, max_length=10, verbose_name='deck gun')),
                ('fwd_torp_tube1', models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='fwd torp tube 1')),
                ('fwd_torp_tube2', models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='fwd torp tube 2')),
                ('fwd_torp_tube3', models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='fwd torp tube 3')),
                ('fwd_torp_tube4', models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='fwd torp tube 4')),
                ('fwd_c35_reloads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='fwd C35/91 reloads')),
                ('fwd_c06_reloads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='fwd C/06 reloads')),
                ('fwd_g6_reloads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='fwd G/6 reloads')),
                ('aft_torp_tube1', models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='aft torp tube 1')),
                ('aft_torp_tube2', models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='aft torp tube 2')),
                ('aft_c35_reloads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='aft C35/91 reloads')),
                ('aft_c06_reloads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='aft C/06 reloads')),
                ('aft_g6_reloads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='aft G/6 reloads')),
                ('gun_damage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='gun damage')),
                ('hull_damage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='hull damage')),
                ('flooding', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='flooding')),
                ('periscope', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='periscope')),
                ('wireless', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='wireless')),
                ('hydro_phones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='hydro phones')),
                ('batteries', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='batteries')),
                ('fwd_torp_door', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='fwd torp door')),
                ('aft_torp_door', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='aft torp door')),
                ('fuel_tanks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='fuel tanks')),
                ('dive_planes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='dive planes')),
                ('kmdt_wound', models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='Commander wounds')),
                ('wound_1wo', models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='1st Officer wounds')),
                ('wound_2wo', models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='2nd Officer wounds')),
                ('li_wound', models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='Engineer wounds')),
                ('doctor_wound', models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='Doctor wounds')),
                ('crew_wound_1', models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='1st crew wounds')),
                ('crew_wound_2', models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='2nd crew wounds')),
                ('crew_wound_3', models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='3rd crew wounds')),
                ('tonnage_sunk', models.IntegerField(default=0, verbose_name='tonnage sunk')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
