# Generated by Django 2.1.7 on 2019-09-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_name', models.CharField(max_length=25, verbose_name='commander name')),
                ('cmd_rank', models.CharField(choices=[('Lt.z.S', 'Lt.z.S'), ('Olt.z.S', 'Olt.z.S'), ('KptLt', 'KptLt'), ('KKpt', 'KKpt')], max_length=10, verbose_name='commander rank')),
                ('bt_name', models.CharField(max_length=3, verbose_name='vessel name')),
                ('bt_class', models.CharField(choices=[('Lt.z.S', 'Lt.z.S'), ('Olt.z.S', 'Olt.z.S'), ('KptLt', 'KptLt'), ('KKpt', 'KKpt')], max_length=10, verbose_name='commander rank')),
            ],
        ),
    ]
