# Generated by Django 2.1.7 on 2019-09-08 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0002_auto_20190908_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='crew_quality',
            field=models.CharField(choices=[('Green', 'Green'), ('Trained', 'Trained'), ('Veteran', 'Veteran'), ('Elite', 'Elite')], default=0, max_length=10, verbose_name='crew quality'),
        ),
        migrations.AddField(
            model_name='boot',
            name='deck_gun',
            field=models.CharField(choices=[('3.7cm', '3.7cm'), ('8.8cm', '8.8cm'), ('10.5cm', '10.5cm'), ('15cm', '15cm')], default=0, max_length=10, verbose_name='deck gun'),
        ),
        migrations.AddField(
            model_name='boot',
            name='gun_damage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='gun damage'),
        ),
        migrations.AlterField(
            model_name='boot',
            name='bt_name',
            field=models.CharField(max_length=4, verbose_name='vessel name'),
        ),
    ]
