# Generated by Django 2.1.7 on 2019-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0003_auto_20190908_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='crew_quality',
            field=models.CharField(choices=[('Green', 'Green'), ('Trained', 'Trained'), ('Veteran', 'Veteran'), ('Elite', 'Elite')], default=1, max_length=10, verbose_name='crew quality'),
        ),
    ]
