# Generated by Django 2.1.7 on 2019-09-08 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0004_auto_20190908_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boot',
            old_name='cmd_name',
            new_name='kmdt_name',
        ),
        migrations.RenameField(
            model_name='boot',
            old_name='cmd_rank',
            new_name='kmdt_rank',
        ),
        migrations.AddField(
            model_name='boot',
            name='aft_c06_reloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='aft C/06 reloads'),
        ),
        migrations.AddField(
            model_name='boot',
            name='aft_c35_reloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='aft C35/91 reloads'),
        ),
        migrations.AddField(
            model_name='boot',
            name='aft_g6_reloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='aft G/6 reloads'),
        ),
        migrations.AddField(
            model_name='boot',
            name='aft_torp_door',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='aft torp door'),
        ),
        migrations.AddField(
            model_name='boot',
            name='aft_torp_tube1',
            field=models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='aft torp tube 1'),
        ),
        migrations.AddField(
            model_name='boot',
            name='aft_torp_tube2',
            field=models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='aft torp tube 2'),
        ),
        migrations.AddField(
            model_name='boot',
            name='batteries',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='batteries'),
        ),
        migrations.AddField(
            model_name='boot',
            name='crew_wound_1',
            field=models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='1st crew wounds'),
        ),
        migrations.AddField(
            model_name='boot',
            name='crew_wound_2',
            field=models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='2nd crew wounds'),
        ),
        migrations.AddField(
            model_name='boot',
            name='crew_wound_3',
            field=models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='3rd crew wounds'),
        ),
        migrations.AddField(
            model_name='boot',
            name='dive_planes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='dive planes'),
        ),
        migrations.AddField(
            model_name='boot',
            name='doctor_wound',
            field=models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='Doctor wounds'),
        ),
        migrations.AddField(
            model_name='boot',
            name='flooding',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='flooding'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fuel_tanks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='fuel tanks'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fwd_c06_reloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='fwd C/06 reloads'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fwd_c35_reloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='fwd C35/91 reloads'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fwd_g6_reloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='fwd G/6 reloads'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fwd_torp_door',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='fwd torp door'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fwd_torp_tube1',
            field=models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='fwd torp tube 1'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fwd_torp_tube2',
            field=models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='fwd torp tube 2'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fwd_torp_tube3',
            field=models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='fwd torp tube 3'),
        ),
        migrations.AddField(
            model_name='boot',
            name='fwd_torp_tube4',
            field=models.CharField(choices=[('N/A', 'N/A'), ('C/06', 'C/06'), ('G/6', 'G/6'), ('C35/91', 'C35/91')], default=1, max_length=10, verbose_name='fwd torp tube 4'),
        ),
        migrations.AddField(
            model_name='boot',
            name='hull_damage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='hull damage'),
        ),
        migrations.AddField(
            model_name='boot',
            name='hydro_phones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='hydro phones'),
        ),
        migrations.AddField(
            model_name='boot',
            name='kmdt_wound',
            field=models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='Commander wounds'),
        ),
        migrations.AddField(
            model_name='boot',
            name='li_wound',
            field=models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='Engineer wounds'),
        ),
        migrations.AddField(
            model_name='boot',
            name='periscope',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='periscope'),
        ),
        migrations.AddField(
            model_name='boot',
            name='wireless',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='wireless'),
        ),
        migrations.AddField(
            model_name='boot',
            name='wound_1wo',
            field=models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='1st Officer wounds'),
        ),
        migrations.AddField(
            model_name='boot',
            name='wound_2wo',
            field=models.CharField(choices=[('N/A', 'N/A'), ('LW', 'LW'), ('SW', 'SW'), ('KIA', 'KIA')], default=0, max_length=10, verbose_name='2nd Officer wounds'),
        ),
    ]
