# Generated by Django 2.1.7 on 2019-09-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0005_auto_20190908_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boot',
            name='tonnage_sunk',
            field=models.IntegerField(default=0, verbose_name='tonnage sunk'),
        ),
    ]
